title: Rui Wang's Homepage
page-top-title: Rui Wang
top-section-bg-text: Artificial Intelligence for Computational Fluid Dynamics
home-subtitle: Rui Wang&ensp;|&ensp;王瑞
copyright-text: '&copy; Rui Wang 2026. All Rights Reserved.'

